# Generated by Django 4.2 on 2025-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=30)),
                ('movie_genre', models.CharField(choices=[('C', 'Comedia'), ('D', 'Drama'), ('F', 'Fantasia'), ('T', 'Terror'), ('A', 'Acción'), ('CF', 'Ciencia Ficción')], max_length=2)),
                ('name_director', models.CharField(max_length=30)),
                ('year_publication', models.DateField(blank=True, null=True)),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
