# Generated by Django 4.2 on 2025-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(choices=[('F', 'Fantasia'), ('A', 'Acción'), ('C', 'Comedia'), ('D', 'Drama'), ('CF', 'Ciencia Ficción'), ('T', 'Terror')], max_length=2),
        ),
    ]
